<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <AssemblyName>Guard Center</AssemblyName>
    <ApplicationIcon>../../Assets/GuardCenter.ico</ApplicationIcon>
  </PropertyGroup>
  <ItemGroup>
    <EmbeddedResource Include="../../../obj/portable-package/payload.zip"
                      LogicalName="GuardCenter.Payload.zip" />
  </ItemGroup>
</Project>
